allowBuilds:
  "@parcel/watcher": false
  "@tailwindcss/oxide": false
  esbuild: false
  sharp: true
  unrs-resolver: false
  vue-demi: false
minimumReleaseAgeExclude:
  - "@nuxt/scripts@1.3.0"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"

onlyBuiltDependencies:
  - sharp
